steps:
### [BUILD APP] ###
  - name: golang:1.19
    id: build-app
    entrypoint: /bin/bash
    args:
    - -c
    - |
      rm -rf bin/helm-wrapper
      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o bin/helm-wrapper

### [BUILD CONTAINER] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: build-container-image
    entrypoint: /bin/bash
    args: ['-c', 'docker build -t gcr.io/${PROJECT_ID}/helm-api:build .']

### [PUBLISH CONTAINER IMAGE] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: publish-container-image
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker tag gcr.io/${PROJECT_ID}/helm-api:build gcr.io/${PROJECT_ID}/helm-api:0.0.2-dev && \
      docker push gcr.io/${PROJECT_ID}/helm-api:0.0.2-dev
