apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-wrapper.fullname" . }}
  labels:
    {{- include "helm-wrapper.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.controllerName }}.{{ .Values.ingress.domainRoot }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-wrapper.selectorLabels" . | nindent 4 }}
